# Generated by Django 4.0.4 on 2022-05-23 12:41

import ckeditor_uploader.fields
from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='corpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
